---
abstract: 'Apache SpamAssassin is an extensible email filter which is used to identify spam'
author:
  - 'The Apache SpamAssassin Project <dev@spamassassin.apache.org>'
build_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.68, CPAN::Meta::Converter version 2.120921'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mail-SpamAssassin
no_index:
  directory:
    - t
    - inc
requires:
  Archive::Tar: 1.23
  Digest::SHA1: 0
  Errno: 0
  File::Copy: 2.02
  File::Spec: 0.8
  HTML::Parser: 3.43
  IO::Zlib: 1.04
  Mail::DKIM: 0.31
  Net::DNS: 0.34
  NetAddr::IP: 4.01
  Pod::Usage: 1.1
  Sys::Hostname: 0
  Test::More: 0
  Time::HiRes: 0
  Time::Local: 0
resources:
  homepage: http://spamassassin.apache.org/
  license: http://www.apache.org/licenses/LICENSE-2.0.html
  repository: http://svn.apache.org/repos/asf/spamassassin/
  x_MailingList: http://wiki.apache.org/spamassassin/MailingLists
version: 3.004002
